[general]
OPENAI_API_KEY="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"
TOGETHER_API_KEY="YOUR-API-KEY"